pool:
  name: Default

stages:
  - stage: Stage1
    jobs:
     - job: Job1

  - stage: Stage2
    dependsOn: Stage1
    jobs:
      - job: job2

  - stage: Stage3
    dependsOn: Stage1
    jobs:
      - job: job3

  - stage: Stage3
    dependsOn: 
    - Stage2
    - Stage3
    jobs:
      - job: job4

