trigger:
- main

pool:
  name: Default

stages:
  - stage: A
    jobs:
      - job: jobA
        steps:
        - task: PowerShell@1
          inputs:
            scriptType: 'inlineScript'
            inlineScript: |
              write-Host "Hello World"
            failOnStandardError: false